name: HyperShop
version: '1.0'
main: me.MILLSBOSS.ecoShop.HyperShop
api-version: '1.21'
supported-versions: [1.21.9, 1.21.10, 1.21.11]
softdepend:
  - Vault
commands:
  shop:
    description: Open the HyperShop
    usage: /shop
    permission: HyperShop.use
permissions:
  HyperShop.use:
    description: Allows using /shop
    default: true
