name: EcoShopPro
version: '1.0'
main: me.MILLSBOSS.ecoShop.EcoShopPro
api-version: '1.21'
softdepend:
  - Vault
commands:
  shop:
    description: Open the EcoShopPro
    usage: /shop
    permission: EcoShopPro.use
permissions:
  EcoShopPro.use:
    description: Allows using /shop
    default: true
